name: Devops 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean verify

    - name: Static Application Security Testing (SAST)
      run: mvn org.owasp:dependency-check-maven:check
      
  test:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run unit tests  
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
    
      - name: Build with Maven
        run: mvn -B package --file pom.xml
    
      - name: Install Ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok
          sudo mv ngrok /usr/local/bin/ngrok
      
      - name: Start Ngrok Tunnel
        run: ngrok http 8080 &
      
      - name: Run Spring Boot App
        run: java -jar target/*.jar &
      
      - name: Wait for Ngrok to start
        run: sleep 10
      
      - name: Get Ngrok Tunnel URL
        id: ngrok_url
        run: echo "::set-output name=url::$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"
      
      - name: Deployed Ngrok URL
        run: echo "Ngrok URL is ${{ steps.ngrok_url.outputs.url }}"
